### ISSUE TITLE
Build version not displaying

### ISSUE THREAD

**Issue by bclarhk** [quipucords/quipucords#994] opened 2018-03-08 20:34 UTC
## Specify type:
- Bug

### Priority:
- Medium
__

## Description:
Build is displaying as "Unknown"

### Version Information:
#991 

![screen shot 2018-03-08 at 3 29 11 pm](https://user-images.githubusercontent.com/32572198/37175005-30b2c29e-22e6-11e8-96a4-8bcebf32801c.png)

**Comment by cdcabrera** [comment] 2018-03-12 13:56
@bclarhk tested this one. Can only partially re-create. Last time we reviewed it returned what appeared to be `Build: master`... looks like it's consistently displaying now...
![screen shot 2018-03-12 at 9 52 30 am](https://user-images.githubusercontent.com/3761375/37287402-22746816-25db-11e8-9e50-1feefa991fc0.png)


Expanding the question/issue to @quipucords/development For local builds what should the build version be coming back as?

**Comment by chambridge** [comment] 2018-03-13 21:46
@bclarhk How are you running this?

My assumption is you are not using the container image being built on Jenkins.

The logic for how the build number is generated comes from the following:
https://github.com/quipucords/quipucords/blob/master/quipucords/quipucords/environment.py#L25

When we build the container image we set the build commit information:
https://github.com/quipucords/quipucords/blob/master/Jenkinsfile#L42

Dockerfile:
https://github.com/quipucords/quipucords/blob/master/Dockerfile#L55

My guess is that when you build locally you are just getting the default `master` as no build-arg is being passed.

Can you clarify what you are seeing? What image you are using, etc.

**Comment by cdcabrera** [comment] 2018-03-13 23:08
hey @chambridge can confirm it's a local Docker build sans-build argument. 

Good to know where the hash is coming from, and that explains the `Build: master` read out. We can close this down @bclarhk since it appears to be working as intended

**Closed** 2018-03-13 23:10 UTC
Labels: UI/UX, bug
