### ISSUE TITLE
Scan type is not updated on a scan when there are scan options

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1854] opened 2019-02-25 15:45 UTC
## Bug Description:
Providing scan options causes other scan changes to be ignored.  It looks like we just don't call instance.save()

### Expected behavior:
Scan should be updated even when options are provided.

### Actual behavior:
Only scan options are updated.

### Steps to reproduce:
Create an inspect scan with the default concurrency.

Run `PATCH` `/api/v1/scans/{id}` with body:
```
{
    "scan_type": "connect",
    "options": {
        "max_concurrency": 200
    }
}
```

The type should now be connect but it is not.  
___

## Acceptance Criteria:

- [ ] Scan is updated with or without options.

___

**Comment by abaiken** [comment] 2019-04-16 19:41
I have tested this on master and I cannot reproduce this bug. Here is what I have done: 
```qpc scan add --name TestScan --source NLargeSource```
Then I do a `PATCH` containing the following info: 
```
{
    "scan_type": "connect",
    "options": {
        "max_concurrency": 200
    }
}
```
Here is the result:
```
{
    "id": 21,
    "name": "TestScan",
    "sources": [
        2
    ],
    "scan_type": "connect",
    "options": {
        "max_concurrency": 200
    }
}
```
Maybe I can get @myersCody to try this tomorrow and if he cannot reproduce the bug either, we can close the issue.

**Closed** 2019-04-17 19:43 UTC
Labels: bug
