### ISSUE TITLE
qpc gives usage message when it can't contact the server

### ISSUE THREAD

**Issue by noahl** [quipucords/quipucords#472] opened 2018-01-23 15:28 UTC
I ran `qpc source list --type network` and got
```
usage: qpc source list [-h] [--type TYPE]

optional arguments:
  -h, --help   show this help message and exit
  --type TYPE  Filter for listing sources by type. Valid values: vcenter, network.
```

I discovered on my own that the server wasn't running. When I got the server up, I ran the same command and got
```
No sources exist yet.
```

which is reasonable.

qpc should tell the user when it can't contact the server, instead of printing usage.

**Comment by kholdaway** [comment] 2018-01-29 15:17
@noahl can you confirm you are still seeing this?

When the server is not configured I see:
```
Please configure server location using command below.
qpc server config --host HOST --port PORT

```
When it is configured but not running I see:
```
A connection error occurred while attempting to communicate with the server. To troubleshoot this problem, check the configuration and the status of the server.
HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api/v1/sources/?source_type=network (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10d641128>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

**Comment by kholdaway** [comment] 2018-01-29 15:26
@noahl If I disable authentication I see:
```
qpc source list --type network
Error: Authentication credentials were not provided.
usage: qpc source list [-h] [--type TYPE]

optional arguments:
  -h, --help   show this help message and exit
  --type TYPE  Filter for listing sources by type. Valid values: vcenter,
               network.
```

@noahl Do you think this is a duplicate of https://github.com/quipucords/quipucords/issues/478?

**Comment by kholdaway** [comment] 2018-01-29 22:29
Closing as duplicate of #478.  Reopen if you disagree.

**Closed by kholdaway** 2018-01-29 22:29 UTC
