### ISSUE TITLE
Satellite 6 scan job leaves a task running when the scan fail

### ISSUE THREAD

**Issue by elyezer** [quipucords/quipucords#1531] opened 2018-09-27 19:50 UTC
## Bug Description:
A task is left running when Satellite 6 scan job fails. The failure seems to be related to quipucords not being able to connect to a server during the inspect task. That makes the entire scan job fail but seems to leave a running task.

### Expected behavior:
No running tasks is left if the scan job fails.

### Actual behavior:
The Scan information shows that the task still running even though the scan job has failed:

```json
{
    "end_time": "2018-09-27T19:37:59.535382",
    "id": 2,
    "options": {
        "max_concurrency": 50
    },
    "scan": {
        "id": 2,
        "name": "a98595bf-0b9e-45c9-bbaf-2959b2ad6f0e"
    },
    "scan_type": "inspect",
    "sources": [
        {
            "id": 2,
            "name": "5ac5b318-d9b2-44ce-a17d-c890472612d6",
            "source_type": "satellite"
        }
    ],
    "start_time": "2018-09-27T19:28:16.776747",
    "status": "failed",
    "status_message": "FATAL ERROR. [Errno -2] Name or service not known",
    "systems_count": 1093,
    "systems_failed": 0,
    "systems_scanned": 150,
    "systems_unreachable": 0,
    "tasks": [
        {
            "end_time": "2018-09-27T19:28:54.623938",
            "scan_type": "connect",
            "source": 2,
            "start_time": "2018-09-27T19:28:16.831255",
            "status": "completed",
            "status_message": "Task is complete.",
            "systems_count": 1093,
            "systems_failed": 0,
            "systems_scanned": 1094
        },
        {
            "scan_type": "inspect",
            "source": 2,
            "start_time": "2018-09-27T19:28:54.628680",
            "status": "running",
            "status_message": "Task is running.",
            "systems_count": 1094,
            "systems_scanned": 150
        }
    ]
}
```

### Steps to reproduce:
Perform a scan job. Not sure if this will be reproducible every time.
___

## Acceptance Criteria:

- [ ] If a scan job fail it should clean up any running task or properly state the task status.

___

### Version Information:
Was playing with the api and the server was on the commit a977aec516a8755e1e58dfccf4178a336673c330

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | Fedora           | 28         | 3.6            | Bare Metal
Target System   | Satellite        | 6          | N/A            | N/A

**Comment by kholdaway** [comment] 2018-09-28 15:00
I actually think this is a duplicate of #1533.  The value for the status message was too long and the task.fail() explodes.  We can keep it open for validation after we fix it.

**Comment by kholdaway** [comment] 2018-10-03 13:39
Should be fixed now.  ScanJob.status_message was converted to a TextField so the length can be much longer.

**Closed** 2018-10-03 13:38 UTC
Labels: bug, component - backend
