### ISSUE TITLE
Possible static certificate/key use

### ISSUE THREAD

**Issue by kseifriedredhat** [quipucords/quipucords#1240] opened 2018-04-17 18:01 UTC
## Specify type:
- Bug

### Priority:
Depends on how it is used (e.g. testing the cert? or used in production, thus allowing MitM?)
___

## Description:
In
https://github.com/quipucords/quipucords/blob/master/deploy/gunicorn.conf.py

# SSL configuration
keyfile = '/etc/ssl/server.key'
certfile = '/etc/ssl/server.crt'

should the key/cert be generated on the fly instead? How exactly is this certificate/key used?
___

## Acceptance Criteria:

-Document if harmless (ideally code comments), fix if not

___

**Comment by kseifriedredhat** [comment] 2018-04-17 18:02
Sorry forgot details, referring to the specific files in:

https://github.com/quipucords/quipucords/tree/master/deploy/ssl

**Comment by chambridge** [comment] 2018-04-17 18:33
This will be documented with the following existing issue:
https://github.com/quipucords/quipucords/issues/595

These files are placeholders for the customer to replace if they wish to enable SSL Certificate Validation between the server and a client. The certificate and keyfile were generated in such a fashion that they are not usable out of the box for SSL Certificate Validation.

I'm going to close this a duplicate of the above issue. Feel free to reopen if this doesn't answer your questions.

**Closed by chambridge** 2018-04-17 18:33 UTC
Labels: bug, duplicate
