### ISSUE TITLE
A user should be able to cancel or pause a Satellite 5/6 connection scan

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1780] opened 2019-01-25 19:20 UTC
### Is your feature request related to a problem?
Satellite connection tasks execute until completion after cancellation.  

### Describe the solution you'd like
Satellite inspection tasks monitor scan manager interrupts and short circuit scans if needed.  Satellite connection tasks should also monitor the interrupts and terminate quickly.

___

## Acceptance Criteria:

- [ ] Satellite 5/6 tasks terminate quickly after the scan manager issues a cancel command.

**Comment by justinkreft** [comment] 2022-06-23 19:12
duplicate of #1813

**Closed** 2022-07-01 15:43 UTC
Labels: feature request, needs_refinement
